parameters:
    manager.notification.services: []
    manager.database.services: []
    manager.package.packages: []
services:
    manager.notification:
        class:     Pkj\LinuxGenericBackup\Manager\NotificationManager
        arguments: ["%manager.notification.services%"]
    manager.database:
        class:     Pkj\LinuxGenericBackup\Manager\DatabaseManager
        arguments: ["%manager.database.services%"]
    manager.package:
        class:     Pkj\LinuxGenericBackup\Manager\PackageManager
        arguments: ["%manager.package.packages%"]
    manager.backup:
        class:     Pkj\LinuxGenericBackup\Manager\NotificationManager
        arguments: ["@service_container"]
